### ISSUE TITLE
qiskit-terra 0.21.2 incompatible installation error

### ISSUE THREAD

**Issue by jmcelroy01** [qiskit-research/qiskit-research#37]
When installing qiskit-research, I get the following message: 

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
qiskit-research 0.1.dev399+g88b5dec requires qiskit-terra==0.21, but you have qiskit-terra 0.21.2 which is incompatible.`

Is the dependency such that qiskit-research will not work with terra 0.21.2? If I try to downgrade terra, pip says that qiskit 0.37.2 requires terra 0.21.2.

**Comment by kevinsung** [comment]
I've relaxed the `qiskit-terra` requirement. Please merge main and try again.

**Comment by kevinsung** [comment]
Closing as this is likely fixed. Let me know if you still have issues.
