### ISSUE TITLE
Kernel dead error 

### ISSUE THREAD

**Issue by hkndoga** [qiskit-research/qiskit-research#72]
Hello! I have been trying to a modified version of the code here https://qiskit-research.github.io/qiskit-research/protein_folding/protein_folding.html

I was able to run it successfully with no issues until a month ago. But now I keep receiving kernel dead error both in VS Code and Jupyter notebook. The kernel dies when I try to run the following line:

raw_result = vqe.compute_minimum_eigenvalue(qubit_op)

Here I attach the juypter log related to the error:

error 11:15:44.140: Error in waiting for cell to complete [Error: Canceled future for execute_request message before replies were done
    at t.KernelShellFutureHandler.dispose (c:\Users\8J6010897\.vscode\extensions\ms-toolsai.jupyter-2023.3.1201040234\out\extension.node.js:2:32419)
    at c:\Users\8J6010897\.vscode\extensions\ms-toolsai.jupyter-2023.3.1201040234\out\extension.node.js:2:51471
    at Map.forEach (<anonymous>)
    at y._clearKernelState (c:\Users\8J6010897\.vscode\extensions\ms-toolsai.jupyter-2023.3.1201040234\out\extension.node.js:2:51456)
    at y.dispose (c:\Users\8J6010897\.vscode\extensions\ms-toolsai.jupyter-2023.3.1201040234\out\extension.node.js:2:44938)
    at c:\Users\8J6010897\.vscode\extensions\ms-toolsai.jupyter-2023.3.1201040234\out\extension.node.js:17:96826
    at ee (c:\Users\8J6010897\.vscode\extensions\ms-toolsai.jupyter-2023.3.1201040234\out\extension.node.js:2:1589492)
    at jh.dispose (c:\Users\8J6010897\.vscode\extensions\ms-toolsai.jupyter-2023.3.1201040234\out\extension.node.js:17:96802)
    at Lh.dispose (c:\Users\8J6010897\.vscode\extensions\ms-toolsai.jupyter-2023.3.1201040234\out\extension.node.js:17:104079)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)]
warn 11:15:44.140: Cell completed with errors {
  message: 'Canceled future for execute_request message before replies were done'

I tried uninstalling/reinstalling jupyter extensions, VS Code, python and anaconda. Nothing seems to fix it. I also recloned the qiskit-research 0.0.1 and installed it. Here are the other details related to my device:

OS: Windows 11
Python: 3.10.10 (I also tried it on 3.9.16)
qiskit               0.42.1
qiskit-aer           0.12.0
qiskit-ibmq-provider 0.20.2
qiskit-terra         0.23.3

Thank you!

**Comment by kevinsung** [comment]
You are running a modified version? Does the original notebook work?

What git commit of qiskit-research are you running?

**Comment by hkndoga** [comment]
I actually tried a few different protein structure to compare and maybe this can help. The error above happened when I ran a longer protein sequence with 15 amino acids. I tried to run a shorter one today with only 6 amino acids and obtained the following error:

ValueError                                Traceback (most recent call last)
Cell In[34], line 1
----> 1 raw_result = vqe.compute_minimum_eigenvalue(qubit_op)
      2 print(raw_result)

File [c:\Users\8J6010897\AppData\Local\anaconda3\lib\site-packages\qiskit\algorithms\minimum_eigen_solvers\vqe.py:546](file:///C:/Users/8J6010897/AppData/Local/anaconda3/lib/site-packages/qiskit/algorithms/minimum_eigen_solvers/vqe.py:546), in VQE.compute_minimum_eigenvalue(self, operator, aux_operators)
    542     opt_result = self.optimizer(  # pylint: disable=not-callable
    543         fun=energy_evaluation, x0=initial_point, jac=gradient, bounds=bounds
    544     )
    545 else:
--> 546     opt_result = self.optimizer.minimize(
    547         fun=energy_evaluation, x0=initial_point, jac=gradient, bounds=bounds
    548     )
    550 eval_time = time() - start_time
    552 result = VQEResult()

File [c:\Users\8J6010897\AppData\Local\anaconda3\lib\site-packages\qiskit\algorithms\optimizers\scipy_optimizer.py:148](file:///C:/Users/8J6010897/AppData/Local/anaconda3/lib/site-packages/qiskit/algorithms/optimizers/scipy_optimizer.py:148), in SciPyOptimizer.minimize(self, fun, x0, jac, bounds)
    145     swapped_deprecated_args = True
    146     self._options["maxfun"] = self._options.pop("maxiter")
--> 148 raw_result = minimize(
    149     fun=fun,
    150     x0=x0,
    151     method=self._method,
    152     jac=jac,
...
--> 241     raise ValueError("Unsupported input to CVaRMeasurement.eval:", type(front))
    243 obs = self.primitive
    244 outcomes = list(data.items())

ValueError: ('Unsupported input to CVaRMeasurement.eval:', )

**Comment by kevinsung** [comment]
What git commit of qiskit-research are you running?

**Comment by hkndoga** [comment]
I believe it is: qiskit_research 0.0.1

**Comment by kevinsung** [comment]
To get the git commit, you can run
```
git rev-parse HEAD
```

**Comment by hkndoga** [comment]
This is what I receive when I run it: 31406c5a986a9b23b775588638d8cfbe17a4b2cb

**Comment by kevinsung** [comment]
You mentioned that you modified the notebook before running it. If you run the notebook exactly as it appears in the repository, without any changes, does it work?

**Comment by hkndoga** [comment]
Yes, I can run the original code with no issues! I realized that when initializing the VQE with CVar, I was supposed to use SamplingVQE.  Sorry for all the trouble and thanks a lot for your help! The code works fine now!

**Comment by kevinsung** [comment]
Ok. Please close this issue if it is resolved.
